Updating SSH Key page for validation
ltb-project/self-service-password pull request #108
Opened 2017-05-06 13:15 UTC by Kage

I updated the SSH Key page to support key bit size checking, as well as some updates for better wording.

I have not yet done the additional languages.  I can do that in a separate pull request if desired, though be warned it will be through Google Translate. ;)

2017-05-06 14:54 UTC, coudot commented
Thanks a lot, I will look at it.

2017-05-08 19:19 UTC, Kage commented
Just pushed an update, because somehow I forgot functions.inc.php :/

2017-07-05 14:08 UTC, plewin requested changes
Other types of keys need to be considered before merging this. Also unit testing of the function that validates the keys would be greatly appreciated.

2017-07-05 14:08 UTC, plewin commented on lib/functions.inc.php
> +    if (count($parts) < 2 || $parts[0] != 'ssh-rsa') { return "keyinvalid"; }
The function considers all non rsa keys as invalid. I do not think it is acceptable to disallow other types of keys : dsa, ecdsa and ed25519.

2017-07-12 17:30 UTC, coudot commented
@Kage and @plewin, do you think you will have time to work on this feature?

2017-10-24 17:09 UTC, Kage commented
Completely forgot about this, I'll look into it soon. :P

2026-04-29 14:20 UTC, closed without merging