Issue 608
ltb-project/self-service-password pull request #619
Opened 2022-01-05 13:53 UTC by doc-slice

Issue #608 
- rename configuration attribute
- aggregate in same function, add/modify objectClass together with sshkey attribute in one operation
- translation not necessary, because no extra messages required
- documentation added

2022-01-05 16:04 UTC, coudot requested changes

2022-01-05 16:04 UTC, coudot commented on conf/config.inc.php
> +$change_sshkey_objectClass = "";
I think we should set the default value to ldapPublicKey, as this is the standard objectClass.

The only impact would be for people using the attribute with another object class, but this should be seldom.

2022-01-06 09:46 UTC, doc-slice commented
default value is now set to ldapPublicKey, documentation adapted

2022-01-06 10:59 UTC, coudot approved these changes

2022-01-06 10:59 UTC, merged

2022-01-06 10:59 UTC, coudot commented
Thanks a lot!